### ISSUE TITLE
Feature: Add endpoint to check if user already vote the repo

### ISSUE THREAD

**Issue by doaortu** [open-sauced/api#129]
### Type of feature

🍕 Feature

### Current behavior

After scanning the [Swagger UI](https://api.opensauced.pizza/#/Repository%20service%20guarded/findAllUserVoted) docs, I noticed there's no quick way to check if user already voted to the specific repository

Right now, I believe, if I want to check any repository already voted by user, I need to fetch the /v1/repos/findAllUserVoted, loop all data and check if there's repo that I want to check, then I finally got the result. Not to mention there's pagination, etc.

### Suggested solution

It would be nice if there's standalone endpoint to do this,
something like /v1/repos/uservoted/{owner}/{repo} or /v1/repos/uservoted/{repoid}
and it will return true or false, with the repo data (voteCount, etc).

if I may, I could help to build this feature.

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by diivi** [comment]
I use this:

```javascript
const upvoteUrl = `https://api.opensauced.pizza/v1/repos/${repoId}/vote`;
fetch(upvoteUrl, {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }).then((response) => {
		if (response.status == 200) {
          console.log("Upvote successful");
		}
		else {
          console.log("Upvote failed")
		}
	});
}
```
Code 409 indicates that the user has already voted for the repo.
