### ISSUE TITLE
Bug: Incorrect example for returned data from `/v1/highlights/{id}/reactions` in swagger

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/api#145]
### Describe the bug

The swagger displays this as an example of the data returned from a request:
![image](https://user-images.githubusercontent.com/52013393/234327316-c5fd61ef-99c1-4123-b180-fb4511da8608.png)

But the actual data format returned when testing was this:
![image](https://user-images.githubusercontent.com/52013393/234327440-afd3909a-00ba-4bd6-b0c6-55a0cc2c51b8.png)

### Steps to reproduce

https://api.opensauced.pizza/#/Highlights%20service/getAllHighlightReactions

### Affected services

api.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@brandonroberts, just wanted to try fixing this issue but I couldn't get the server up and running. I tried my own supabase instance but couldn't get it connected. Is there a dev env that I can use or another way to start the app?
