### ISSUE TITLE
Feature: Inconsistency between documentation and result

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/api#174]
### Type of feature

📝 Documentation

### Current behavior

When I was working on https://github.com/open-sauced/ai/pull/101 I found out that I got this result from the /highlight post endpoint: 
![image](https://github.com/open-sauced/api.opensauced.pizza/assets/18273833/140fc384-fdea-4d4c-bf21-7f10141bcd9c)

In the swagger documentation, it's mentioned that I will get the ID of the highlight: 
![image](https://github.com/open-sauced/api.opensauced.pizza/assets/18273833/9b16074a-a33e-4245-933d-f255d5d40097)

Which was not the case. 

https://api.opensauced.pizza/#/User%20Highlights%20service/addHighlightForUser

### Suggested solution

Either update the swagger docs, or add the id. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by GaganSingh5** [comment]
Hi, Can I contribute to this issue?

**Comment by brandonroberts** [comment]
> Hi, Can I contribute to this issue?
> 

Sure. Each endpoint is documented with Swagger, so you can look there at the model.
