### ISSUE TITLE
Feature: rename this repo to api

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/api#188]
### Type of feature

📦 Chore

### Current behavior

The name for the repository matches the domain name. It doesn't necessarily need to, and makes the name longer than it needs to be.

This renames this repo to `api` and updates the associated places its used for deployment, releases, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@brandonroberts per my changes to other repos, I don't believe changing the name will break much. GitHub has decent 301 redirects, as long as we don't change the name twice. 

I will go ahead and make that change now.

**Comment by brandonroberts** [comment]
Ok cool
