### ISSUE TITLE
Feature: integrate `pizza` service with API

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#218]
### Type of feature

🍕 Feature

### Current behavior

Currently, [the `pizza` oven service](https://github.com/open-sauced/pizza) (which indexes and processes commits on repositories) is not integrated in the API.

Ideally, we want a _single_ API layer for all things OpenSauced.

### Suggested solution

Let's integrate the pizza oven service into the API. Initially, I'd imagine a few routes:

Get commits for a repository:
```
/v1/repos/{id}/commits
```

Bake a repository (which will send the request to the Pizza oven service to then do all the indexing):
```
/v1/repos/{id}/bake
```

This involves a few things:
- Aligning the database design with what the `pizza` oven service (cc @brandonroberts) so that the API can also consume the indexing from the pizza oven through to the API
- Align the above 2 initial routes (does it make sense that these would live on the `/v1/repos` endpoint?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Chatted with @brandonroberts this morning, and we're thinking we'll need to make a few changes:
- Create 3 new tables on the database that align with the `pizza-oven` service's data (which is only processing commits, not git service provider data):
    - `baked-repos`: A table of ids and urls that have been processed by the pizza-oven service
        - This will act as the sort of "bridge" table to link the existing GitHub data in the API and the data the pizza oven service generates
    - `commit-authors`: A table of ids and emails associated with commits
    - `commits`: Which has a foreign key to the `baked-repos` and `commit-authors`. This table contains all the commit data.
    - Then, the `pizza-oven` service can be aligned to write data into the API's postgres database.

- `/v1/repos/{id}/commits` can be used to get the commits for an individual GitHub repo. This may also involve abit of work getting the two tables to "link" but might just be an SQL query.

- `/v1/bake/{git-url}` would probably be a better endpoint the CLI and other clients can use to forward post requests to the `pizza-oven` service. This way, it's not linked to the ID of a GitHub entry in the database.

**Comment by bdougie** [comment]
Related extra information. 

While working last night noticed the term mannequins. Contributions without a github user. Thinking about the duplication work we will need to do is similar. While we list commits, we might need to identify commits that may be stood up by a mannequin

<img width="1157" alt="Screen Shot 2023-07-24 at 11 57 55 PM" src="https://github.com/open-sauced/api/assets/5713670/38be807b-0a48-4f59-8a37-8842ad4e6c48">
