### ISSUE TITLE
Feature: document necessary env vars to run database and do local dev

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#226]
### Type of feature

🍕 Feature

### Current behavior

1. Currently, there's not alot of documentation on the actual env vars that are necessary to run the API, just the supabase credentials. This may be especially confusing for the logging database.
2. New comers may be confused how to use the various `migrations/` and how to bootstrap a new database locally for local dev

### Suggested solution

We should document all the env variables necessary to standup the API:

```env
# Supabase creds for user auth
SUPABASE_URL="my-supabase-url.supabase.com"
SUPABASE_API_KEY="abc123 ..."
SUPABASE_JWT_SECRET="abc123 ..."
API_DOMAIN=""

# Postgres db for the API
TYPEORM_CONNECTION=postgres
TYPEORM_HOST_API=localhost
TYPEORM_PORT_API=25060
TYPEORM_USERNAME_API=doadmin
TYPEORM_PASSWORD_API=password
TYPEORM_DATABASE_API=defaultdb
TYPEORM_SYNCHRONIZE_API=false
TYPEORM_SSL_CERT_API="-----BEGIN CERTIFICATE-----\n ..."

# Postgres db for logs (can be the same as the normal API database)
TYPEORM_CONNECTION_LOGGING=postgres
TYPEORM_HOST_LOGGING=url.to.db.host
TYPEORM_PORT_LOGGING=25060
TYPEORM_USERNAME_LOGGING=doadmin
TYPEORM_PASSWORD_LOGGING=password
TYPEORM_DATABASE_LOGGING=defaultdb
TYPEORM_SYNCHRONIZE_LOGGING=false
TYPEORM_SSL_CERT_API_LOGGING="-----BEGIN CERTIFICATE-----\n ..."
```

---

Additionally, we should document using the normal database as the logging database.

---

And finally, we should document using `psql` to apply migrations to a local postgres database so that it can be easily used for local development:

```bash
export PGPASSWORD=my-password

for file in migrations/*; do 
  psql -h localhost -p 25060 -U doadmin defaultdb -f "${file}"
done
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
NICE! The shell script is very well needed. I remember executing migration files one by one 💀

Bonus: We can also bring back seed data from the history https://github.com/open-sauced/api/blob/c6c07c6e4f48911a919d50c55724f3e1e3584bdf/supabase/seed.sql
