### ISSUE TITLE
Feature: add username to the notifications and remove highlight id in the message

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/api#247]
This error may due to the notification meta_id being used here. We have access to the user id, but we cache users based on usernames.

We will probably need an API update to include username. 

https://github.com/open-sauced/insights/pull/1478/files#diff-2524a786a0bcb5deadfbb244b5d5ef18304b923e055b9f64c1dd9fd0c695a592R158

We will also don't need to add the meta_id to the message. Weird seeing `239 BekahHW did a thing`

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1529#issuecomment-1670690257_

**Comment by takanome-dev** [comment]
In the example above 239 is the highlight ID. The user does not need to see that in the text, to be clear keeping that in the response from the API is expected.

There is no value with having 239 in my notification. That needs to be removed in the UI.

This should be a straight forward API update.

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1529#issuecomment-1671242828_

**Comment by takanome-dev** [comment]
## Suggested Solution

We can add "from" user information to each notification in the API.

Here is an example
https://github.com/open-sauced/api/blob/beta/src/user/user.entity.ts#L522
https://github.com/open-sauced/api/blob/beta/src/user/entities/user-collaboration.entity.ts#L53

The meta_id field should be used along with the type to build the URL of where it should link to, which is what we had in the UI before with the notification bell.

_Originally posted by @brandonroberts in https://github.com/open-sauced/insights/issues/1529#issuecomment-1671389552_

**Comment by takanome-dev** [comment]
.take

**Comment by takanome-dev** [comment]
cc @brandonroberts How did you add the emojis in the db?
I'm trying to test this but need some emojis first.

**Comment by brandonroberts** [comment]
Here's a list of the emojis we use

```
INSERT INTO public.emojis VALUES ('f78c0d0a-502e-45fd-a565-db67b3f22135', 'tada', 'https://github.githubassets.com/images/icons/emoji/unicode/1f389.png?v8', '2023-04-11 07:49:10', '2023-04-11 07:49:11', NULL, 4);
INSERT INTO public.emojis VALUES ('822747bd-fd99-4fc3-b7ca-41032afcbaad', 'eyes', 'https://github.githubassets.com/images/icons/emoji/unicode/1f440.png?v8', '2023-04-07 08:11:11', '2023-04-07 08:11:13', NULL, 8);
INSERT INTO public.emojis VALUES ('07d22c68-621d-4537-a6dd-3dddc7691035', 'pizza', 'https://github.githubassets.com/images/icons/emoji/unicode/1f355.png?v8', '2023-04-07 08:10:23', '2023-04-07 08:10:25', '2023-04-11 07:51:22', 4);
INSERT INTO public.emojis VALUES ('9634048c-f11f-4dfc-828b-bddab0a0443f', 'rocket', 'https://github.githubassets.com/images/icons/emoji/unicode/1f680.png?v8', '2023-04-07 08:10:55', '2023-04-07 08:10:56', NULL, 7);
INSERT INTO public.emojis VALUES ('e2cc680c-9f02-4667-94a2-958c9c759f0f', '100', 'https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png?v8', '2023-04-07 08:09:22', '2023-04-07 08:09:27', '2023-04-11 07:51:01', 1);
INSERT INTO public.emojis VALUES ('b28107be-019a-4b68-be59-5ea6f293ae8e', 'heart', 'https://github.githubassets.com/images/icons/emoji/unicode/2764.png?v8', '2023-04-07 08:10:39', '2023-04-07 08:10:42', NULL, 6);
INSERT INTO public.emojis VALUES ('da211c29-df2e-40a7-be98-edea7fbe6100', '-1', 'https://github.githubassets.com/images/icons/emoji/unicode/1f44e.png?v8', '2023-04-11 07:44:36', '2023-04-11 07:44:38', '2023-04-17 09:13:39', 2);
INSERT INTO public.emojis VALUES ('27808cb4-2e40-4b11-a272-c15e5ecec62d', '+1', 'https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png?v8', '2023-04-07 08:09:57', '2023-04-07 08:09:57', '2023-04-17 09:13:35', 1);
INSERT INTO public.emojis VALUES ('4780e398-b113-4586-933b-7d8f59e56659', 'confused', 'https://github.githubassets.com/images/icons/emoji/unicode/1f615.png?v8', '2023-04-11 07:47:42', '2023-04-11 07:47:44', '2023-04-17 09:16:03', 5);
INSERT INTO public.emojis VALUES ('0767396f-a78a-429a-9236-cd310768e547', 'smiley', 'https://github.githubassets.com/images/icons/emoji/unicode/1f603.png?v8', '2023-04-07 08:10:11', '2023-04-07 08:10:12', NULL, 3);
```
