### ISSUE TITLE
Error 401 at User Collaboration Service

### ISSUE THREAD

**Issue by babblebey** [open-sauced/api#292]
Very well @BekahHW, after some testing I think the issue is from the endpoint itself, nothing peculiar to the client-side, this is because I have also tested the endpoint ([User Collaboration Service](https://beta.api.opensauced.pizza/#/User%20Collaborations%20service/addUserCollaboration)) via swaggerUI, same 401

![image](https://github.com/open-sauced/app/assets/25631971/a3e007ce-e2d3-4ca6-a40a-7baf02d9b020)

Though I saw it required authorization, i.e. a `sessionToken` from client present when a user is logged in, but in the presence of that, the 401 error persists... this error code isn't specifically documented, so I cannot deduce exactly what it means different from being `Unauthorized`.

I'd like @jpmcb and @OgDev-01 to take a look at this.

_Originally posted by @babblebey in https://github.com/open-sauced/app/issues/1632#issuecomment-1704327645_

**Comment by jpmcb** [comment]
Weirdly, doing a "get" on the collaborations is fine:

```
curl -X 'GET' \
  'https://api.opensauced.pizza/v1/user/collaborations?page=1&limit=10&range=30' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'
```

```json
{
  "data": [],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 0,
    "pageCount": 0,
    "hasPreviousPage": false,
    "hasNextPage": false
  }
}
```

I'm not seeing the difference in our decorators that would indicate a misconfiguration with our nest routes:

https://github.com/open-sauced/api/blob/4f55a8964c3daafae0cf9a6d0618055aad8f9cda/src/user/user-collaboration.controller.ts#L62-L68

**Comment by takanome-dev** [comment]
Oh, this is a permission issue, see https://github.com/open-sauced/api/pull/189

https://github.com/open-sauced/api/blob/2d08206998303ce31b4990b9ca91dd9239a8734b/src/user/user-collaboration.controller.ts#L81-L87

@brandonroberts I thought a user with a role `50` should be able to request collaborations, I honestly have no clue what what those numbers means :sweat_smile:

**Comment by babblebey** [comment]
Hahaha 😂 @takanome-dev 

So IMK, role `50` are premium users with paid/upgraded access and `10` are free users.

**Comment by brandonroberts** [comment]
That's correct. Collaborations work two-fold. The person requesting the collaboration has to be an upgraded user, and the recipient has to have opted-in to receive collaboration requests in their user profile.


![image](https://github.com/open-sauced/api/assets/42211/e3e74b75-2469-4ba9-87ee-13d1707721a4)

**Comment by brandonroberts** [comment]
> 

This is a bug though, as a role of `50` should be allowed to send collaboration requests

**Comment by jpmcb** [comment]
https://github.com/open-sauced/api/blob/2d08206998303ce31b4990b9ca91dd9239a8734b/src/user/user-collaboration.controller.ts#L81-L83

`50 <= 50` will always be true (since the "less than or equal to" is inclusive). Since it seems that most paid users with those roles get assigned "50", the quickfix is to change this to:

```ts
 if (requester.role < 50) { 
   throw new UnauthorizedException(); 
 } 
```

in order to _not_ be inclusive of users with role 50 assigned.

**Comment by brandonroberts** [comment]
Agreed. We kept the structure loosely defined upfront to provide flexibility to pivot if needed. We could be changing this soon to a more structured flagging system, so I would go for the short term fix.

**Comment by babblebey** [comment]
> That's correct. Collaborations work two-fold. The person requesting the collaboration has to be an upgraded user, and the recipient has to have opted-in to receive collaboration requests in their user profile.

If this is the case i.e. Collaboration Request feature is only reserved to Paid/Upgraded Users, then I think we might want to properly document the `401` error message as a feature not allowed based on user role than just plain `Unauthorized`>

Then we can take to the client-side, alerting user of the restrictions to the Collab Request feature, stating it's only for paid users when they try to submit these requests.
