### ISSUE TITLE
Bug: Readme.md - Error in local setup

### ISSUE THREAD

**Issue by EthenThinkful** [open-sauced/api#300]
### Describe the bug

Where the error occurs in the readme: 
![openssl-cert-readme-section](https://github.com/open-sauced/api/assets/104235709/2645989a-e6ec-4046-8efb-605bbc9279ce)

After running the above command, I get this back in my console:
![openssl-cert-error](https://github.com/open-sauced/api/assets/104235709/f1a37d05-d22d-4225-9ba7-d207da38138a)

### Steps to reproduce

1. Clone a new fork locally
2. Create a new Supabase project and set the credentials in an env file
3. Run the OpenSSL command in your terminal under /dev directory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Looks like you're on windows with MINGW64 and it's using your local directory path as part of the `-subj` name.

From some quick searching around, it seems you need to escape the `/` so it doesn't attempt to use that as a file path. Maybe give this a try?

```sh
openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes -subj "//CN=localhost"
```

**Comment by EthenThinkful** [comment]
This worked, thanks!
