### ISSUE TITLE
Bug: Local Setup No SSL Support

### ISSUE THREAD

**Issue by EthenThinkful** [open-sauced/api#302]
### Describe the bug

After following all the steps in the Readme.md to set up the API locally, when I run 'npm run start:dev', I get this error below:
![nosupportssl](https://github.com/open-sauced/api/assets/104235709/127b6bb4-ca80-44ec-8cd5-3fb4f4db16bf)

### Steps to reproduce

1. Fork, clone, and follow steps in Readme to set up API locally
2. Run 'npm run start:dev'
3. See error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
You're getting this (likely) since your postgres isn't setup to accept SSL connections so when the nest server attempts to ping it, it fails. How did you setup postgres on your dev machine?

**Comment by EthenThinkful** [comment]
I'm assuming I'd have to enable the pg_hba.conf file as shown below to accept SSL connections?

![pg_hba](https://github.com/open-sauced/api/assets/104235709/5a4b5f33-16f7-4533-ac1e-d15fe2b9a98d)

**Comment by EthenThinkful** [comment]
Here is my postgresql.conf file as well:
![postgresqlconf](https://github.com/open-sauced/api/assets/104235709/2871ff67-5efc-4933-a49b-9427e602ad4a)

**Comment by EthenThinkful** [comment]
I'm running it on docker with the scripts from the Readme:
![settinguppostgresql](https://github.com/open-sauced/api/assets/104235709/1cb2e5e1-e9b9-4905-ac52-91919f0a2971)

However, the Readme did not mention to explicitly run the "init-docker-ssl.sh". When I try and run "init-docker-ssl.sh" I get back: 
![dockertry](https://github.com/open-sauced/api/assets/104235709/02237aa3-be0c-463d-8ab8-fa47b2c2bd6b)

**Comment by jpmcb** [comment]
Right, the `init-docker-ssl.sh` is used as the entrypoint for the Docker container: what output do you get when building and running the docker container?

**Comment by EthenThinkful** [comment]
Here's a snippet of that part: 

https://github.com/open-sauced/api/assets/104235709/18c964b4-4010-4ca5-9e9b-1c9efa194a3e

**Comment by EthenThinkful** [comment]
Output when running "docker build -t my_postgres_image -f Dockerfile.local-postgres .":
![dockerfileoutput](https://github.com/open-sauced/api/assets/104235709/b8b96829-6784-44c3-8868-c98a24101b71)

**Comment by jpmcb** [comment]
Looks like everything is running fine: you won't need to run `init-docker-ssl.sh` since that script gets automatically injected into the container and run at container start time.

With that container running in the background, what's the full output from running `npm run start:dev`? Also important to check that your `.env` file is setup correctly!

**Comment by jpmcb** [comment]
You might want to try running the docker container in interactive mode and see if that gives you some log output for why it's rejecting the SSL connection:

```
docker run -it --rm --name api-db -p 25060:5432 my_postgres_image:latest
```

**Comment by EthenThinkful** [comment]
Quick question: Does my local .conf psql settings matter if I'm going off scripts within the project? 

Here's the output of running that in interactive mode. I don't know what could point to why it's rejecting SSL connections:
![interactivemodeoutput](https://github.com/open-sauced/api/assets/104235709/2138ffb6-8a53-467a-84de-992432cdf3bb)

**Comment by jpmcb** [comment]
Hmm there's the problem: the container isn't getting the file correctly. I bet this is an issue with Windows vs MacOS (linux like) setup for Docker. If you can exec into that container and see where the file is, that'll be helpful!

**Comment by EthenThinkful** [comment]
So here are the logs from within docker when I try and run the container:

![logsfromrunningcontainer](https://github.com/open-sauced/api/assets/104235709/4b187ad6-5573-4ca0-8ab9-51960899876a)

In the last line of the logs it has the path "/usr/local/bin/docker-entrypoint.sh" stating the required file is not found, however when I navigate to that file from within the container in the Docker files it's here: 
![usrlocalbinentrypoint](https://github.com/open-sauced/api/assets/104235709/5c513b4b-fb59-4f1f-89ab-100305a69971)

**Comment by EthenThinkful** [comment]
Here is the file it is looking for!
![foundthefile](https://github.com/open-sauced/api/assets/104235709/da7e7d77-9530-4992-b250-771563b7fc5b)

**Comment by jpmcb** [comment]
The file's there. But it's not seeing it when the docker context attempts to execute it. My guess is that Window's isn't getting the path correctly since this was built from a MacOS (linux like) system and the paths are different in the Window's context.

A few things to try:

This bit is where the file paths are being dropped in for the docker context to execute the container initiation. Maybe try modifying those to be more window's like?
https://github.com/open-sauced/api/blob/6d83068a6538fe3920b4674d0836cb58f34c179f/dev/Dockerfile.local-postgres#L27-L30

I can also try to mess with this on window's abit although, generally, we won't offer great support for doing local dev on Windows.

**Comment by EthenThinkful** [comment]
I'm getting Ubuntu up and running on my machine and then going to re-try this process!

**Comment by EthenThinkful** [comment]
I have successfully got this thang running locally after getting Ubuntu
