### ISSUE TITLE
Bug: `/v1/contributor/insights/` shouldn't allow taking empty `repoIds`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#306]
### Describe the bug

This chunk is used to get some metrics for the `contributors/insights/*` endpoints:

https://github.com/open-sauced/api/blob/6d83068a6538fe3920b4674d0836cb58f34c179f/src/pull-requests/pull-request.service.ts#L282-L299

Notice that if `repoids` is empty, it skips adding the `IN` statement for the repoid array.

In the actual controller for the API endpoint, we allow for empty repoids which in turn _will search all pull requests and metrics for all repos_ across the entire database.

I tried this on the swagger page and after about 10 minutes, the query timed out.

![Screenshot 2023-09-18 at 9 31 22 AM](https://github.com/open-sauced/api/assets/23109390/f8d83152-925f-49b5-b93d-8c3e4ed2741f)

### Steps to reproduce

1. Query one of the `v1/contributors/insights/*` endpoints
2. Do not supply a `repoIds` field
3. Notice that the query takes a very long time to return (but most likely times out)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Hack-Light** [comment]
@jpmcb i can also push a fix for this

**Comment by takanome-dev** [comment]
> i can also push a fix for this

@Hack-Light, feel free to open a pr
