### ISSUE TITLE
Feature: support pull request reviews

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#321]
### Type of feature

🍕 Feature

### Current behavior

We should start indexing who reviews a pull request:

```
reviewed_by_login = ['bdougie', 'brandonroberts', 'jpmcb']
```

Currently, we have no way to surface who reviewed a pull request.

### Suggested solution

We should add a column in the `pull_requests` table that would (probably?) be an array of user logins that have reviewed a pull request.

We'd also need to support a backfill on prs in the ETL for this (since reviews are more dynamic and may update minute by minute).

---

Tangentially related to https://github.com/open-sauced/app/pull/1594

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
One thought @jpmcb and @isabensusan. What if we made this opt in, so we didn't have to backfill. Perhaps there is a button or note stating you can see PR reviews too if you do this action. Not sure what that action is yet, but perhaps flag in settings.
