### ISSUE TITLE
Bug: a few spots with commited merge conflict bits

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#324]
### Describe the bug

There are a few places that have merge conflict decorators that have been committed.

Example:

https://github.com/open-sauced/api/blob/412f1e4194eeb0633b2baceb71ef79c923f8695c/npm-shrinkwrap.json#L1-L17

### Steps to reproduce

```
❯ rg HEAD
npm-shrinkwrap.json
3:<<<<<<< HEAD
13:<<<<<<< HEAD

CHANGELOG.md
193:<<<<<<< HEAD
210:<<<<<<< HEAD
```

The changelog one looks minor but we should probably address the shrinkwrap one

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Hack-Light** [comment]
Hey good day @jpmcb can i make a PR with a fix for this
