### ISSUE TITLE
feat: add endpoint to get timezones based on data from our database

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/api#337]
Curious if we should only show times zones that returns results. Is that possible?

_Originally posted by @bdougie in https://github.com/open-sauced/app/issues/1747#issuecomment-1739822386_

**Comment by OgDev-01** [comment]
According to https://github.com/open-sauced/app/pull/1747#issuecomment-1739877461 i can source out all timezones that are available in contributors table right? cc: @brandonroberts

**Comment by brandonroberts** [comment]
> According to [open-sauced/app#1747 (comment)](https://github.com/open-sauced/app/pull/1747#issuecomment-1739877461) i can source out all timezones that are available in contributors table right? cc: @brandonroberts

It would be from the users table, along with filtering out empty values

**Comment by OgDev-01** [comment]
Ok... thanks

**Comment by brandonroberts** [comment]
If this is the only thing holding up the UI PR, I'd say let's move forward with what we have and refactor to use the API when its ready

**Comment by OgDev-01** [comment]
> If this is the only thing holding up the UI PR, I'd say let's move forward with what we have and refactor to use the API when its ready

Agreed 👍
