### ISSUE TITLE
Feature: support `/v1/users/{username}/following`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#344]
### Type of feature

🍕 Feature

### Current behavior

We currently don't have any way to support who a user follows on GitHub --> OpenSauced, especially for insight pages.

### Suggested solution

Support a `following` array of users logins (from GitHub) that is associated to the user login of the person that user follows on GitHub. This would likely be a modification to the `users` table to accommodate a list of other users. Or possible another table that can be left joined on.

This would also include changes to our backfilling process to backfill the users someone follows.

This would then support the ability to have a `/v1/users/{username}/following` endpoint for the payload of users a given `username` follows.

### Additional context

Related to upcoming list feature work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jobayer12** [comment]
@jpmcb 
1. Is this API only for authenticated users?
2. Which one is the login API and how to get the jwt token in the local environment?

**Comment by jpmcb** [comment]
@jobayer12 - good questions:

1. Seeing as the following/followers for GitHub users aren't private in any way, this probably doesn't need to be auth guarded. The current `GET v1/users/{username}` isn't guarded so this shouldn't need to be
2. You'll want to follow steps for setting up your supabase instance (since we use that for auth to GitHub): https://github.com/open-sauced/api?tab=readme-ov-file#-setting-up-your-supabase-instance

Are you wanting to try tackling this? Let me know if you have questions!

**Comment by jobayer12** [comment]
@jpmcb I tried to implement this feature and created a draft pull request. However, I have no data in my local database. But write code based on the follower list feature. I'm trying to generate data in my local database.

**Comment by jpmcb** [comment]
We don't really have a great way to seed development data right now and this has been a persistent problem for people contributing to this codebase. We have some ideas in the works but for now, if you have your supabase setup, you can also run the frontend to get your account setup and see some stuff flowing through.

See:

https://github.com/open-sauced/api/issues/304
