### ISSUE TITLE
Feature: Most Active Contributors endpoint should support `total_contributions`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#347]
### Type of feature

🍕 Feature

### Current behavior

There's not a great way to get the "total" number of contributions for each individual contributor, a sum of all the contributions, from the paginated endpoint:

```
/v1/lists/{id}/stats/most-active-contributors
```

A consumer would have to iterate all pages to get the total.

### Suggested solution

Instead, the API should support a "total" for this pagination:

```json
{
  "data": [
    {
      "login": "bdougie",
      "commits": 0,
      "prs_created": 0,
      "prs_reviewed": 0,
      "issues_created": 0,
      "comments": 0
      "totalContributions": 123,
    }
  ],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 100,
    "pageCount": 10,
    "hasPreviousPage": false,
    "hasNextPage": true
  }
}
```

---

cc @nickytonline as this relates directly to https://github.com/open-sauced/app/pull/1796

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
.take

**Comment by nickytonline** [comment]
Just for clarificatoin on this @jpmcb, it's for each user, not the total contributions of all users. So probably a calculated field.

**Comment by nickytonline** [comment]
Actually, looking at the logic again, it's both. 😅 So the shape would be like so.

```diff
{
  "data": [
    {
      "login": "bdougie",
      "commits": 0,
      "prs_created": 0,
      "prs_reviewed": 0,
      "issues_created": 0,
      "comments": 0
      "total_contributions": 123,
    }
  ],
  "meta": {
    "page": 1,
    "limit": 10,
+	"all_contributions"
    "itemCount": 100,
    "pageCount": 10,
    "hasPreviousPage": false,
    "hasNextPage": true
  }
}
```

It's currently handle in the code but that only works for the current page of data, i.e.

```
const allContributions = data.reduce((acc, curr) => acc + curr.total_contributions, 0);
```

**Comment by nickytonline** [comment]
I'm wrapping up the filtering based on contributor type for the most active graph on the list activity page, and then I will look at this unless you get to it first @jpmcb. 🏃

**Comment by jpmcb** [comment]
I'm ready! I'll snag this so we can tackle it in parallel 👏
