### ISSUE TITLE
Bug: Ordering by commits DESC for the lists/{listId}/stats/most-active-contributors results in null values being first

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/api#348]
### Describe the bug

Commit counts that are `null` show up as the contributor with the most contributions.

### Steps to reproduce

1. Go to swagger and ensure you're logged on with for the beta API, https://beta.api.opensauced.pizza/#/User%20Lists%20service/getMostActiveContributors
2. Run the most active contributors endpoint with the list ID, `23c2ca69-7667-4b6a-ad2e-d402999af310`, e.g. `lists/{listId}/stats/most-active-contributors?page=1&limit=10&orderDirection=DESC&range=30&prev_days_start_date=0&orderBy=commits`
3. Notice that the first user has no commits even though they are the first in the list. Their commits are `null`.

```json
{
  "data": [
    {
      "login": "0-vortex",
      "commits": null,
      "prs_created": 0
    },
    {
      "login": "nickytonline",
      "commits": 292,
      "prs_created": 21
    },
    {
      "login": "brandonroberts",
      "commits": 275,
      "prs_created": 44
    },
    {
      "login": "OgDev-01",
      "commits": 184,
      "prs_created": 15
    },
    {
      "login": "BekahHW",
      "commits": 52,
      "prs_created": 11
    },
    {
      "login": "jpmcb",
      "commits": 26,
      "prs_created": 15
    },
    {
      "login": "bdougie",
      "commits": 15,
      "prs_created": 4
    },
    {
      "login": "isabensusan",
      "commits": 11,
      "prs_created": 1
    }
  ],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 8,
    "pageCount": 1,
    "hasPreviousPage": false,
    "hasNextPage": false
  }
}
```

It probably makes more sense for the default value to be 0?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Relates to the work in https://github.com/open-sauced/app/pull/1796

**Comment by jpmcb** [comment]
Hmmm weird. I can take a look at this if it's not stepping over what you're also working in the API on @nickytonline ?

**Comment by nickytonline** [comment]
I haven't started work on my API fix, so go for it.

**Comment by jpmcb** [comment]
Cool beans! I found the problem: we were missing a `COALESCE` when counting the `commits`. So the following small patch should fix it

```
(SELECT COALESCE(SUM("pull_requests"."commits"), 0)
```

.take
