### ISSUE TITLE
Feature: POST to /v1/user/{username}/follows should support mass follow by usernames

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/api#389]
### Type of feature

🍕 Feature

### Current behavior

In order to follow multiple people, the https://api.opensauced.pizza/#/User%20service/followUserById has to be called multiple times.

This would create a new endpoint for PUT to `/v1/users/{username}/follows` to provide an array of usernames to follow in bulk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
I can snag this @brandonroberts if you're not already working on it?
