### ISSUE TITLE
Bug: orgs are included when searching for list contributors

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/api#415]
### Describe the bug

When using the [/v1/lists/contributors](https://api.opensauced.pizza/#/User%20Lists%20service/getContributors) endpoint, organizations are included in the search results, and it should only be users.

### Steps to reproduce

Use the endpoint and see user type of 'Organization'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
👀 I can .take this
