### ISSUE TITLE
Annoucement 🚨 `v2` breaking changes 

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#478]
In an effort to migrate away from data scrapped off of GitHub’s API and move to our new events based data stored in Timescale, OpenSauced engineering will be cutting a new, breaking `v2` of the OpenSauced API.

Given there are few direct consumers of the API outside of the `open-sauced` org, there will be _no transition period between the `v1` and `v2` API_. Client consumers (like `open-sauced/app`, `open-sauced/hot`, `open-sauced/pizza-cli`, etc.) should anticipate these breaking changes and release concurrently with beta and prod releases of the API.

So, for example:

```
GET v1/auth/session
```

will become

```
GET v2/auth/session
```

regardless of functionality change.

---

### But wait! I consume the OpenSauced API!

Fabulous! We'd love to learn more about your use case, how you consume the OpenSauced API, and how we can work with you to make this a smooth transition for you! In general, most routes will not change and you should be ok with removing/replacing `v1` with `v2`.

### When will this happen?

We will keep this issue up to date on when this will happen but we will eventually cut these changes into `beta` from `alpha` and then into `main` from `beta`. Keep an eye on those branches to stay in the loop.

### What's changing in the API?

All routes will now start with `v2`, there will be a few new routes, some data will be mutated in a few routes, and several routes are being removed.

This issue will be kept up to date with what's happening as we complete this work.

**Comment by bdougie** [comment]
Thanks for this @jpmcb. Commenting to subscribe and ensure I create a transition plan for the following:

- [ ] open-sauced/hot
- [ ] open-sauced/ai
- [ ] open-sauced/contributor.info

**Comment by jpmcb** [comment]
V2 has been released 🐙 https://github.com/open-sauced/api/pull/524
