### ISSUE TITLE
v2 API: error if `repos`, `repoIds`, nor `topic` is provided

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#496]
The V2 API should throw an error where a user doesn't provide either `repos`, `repoIds` nor a `topic`. This change is two-fold:

- Non of those options should be explicitly required. So, for endpoints (like the PR histogram endpoint) that require `repos` be provided in the DTO, this requirement should be removed.
- An error should be raised if a user attempts to make an extremely broad query _without_ one of those options. This would cause a full table scan of all contributors within the given time window for our events data.

**Comment by brandonroberts** [comment]
Closed via https://github.com/open-sauced/api/pull/501
