### ISSUE TITLE
Feature: v2 API - consider deprecating `prs/list` in favor of `prs/search`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#497]
### Type of feature

🧑‍💻 Refactor

### Current behavior

The `v2/prs/list` functionality is problematic: as is, 1:1 from how it worked in `v1/prs/list`, it will scan _all_ `pr` events in the given range window.

In one experiment, this was over 3,745,045 prs that Timescale had to scan before returning a result (which took about 1-2 minutes).

### Suggested solution

We should consider taking the opportunity to deprecate `prs/list` in favor of more granular (and much faster) `prs/search`

I'm not certain the client / app impact this would have: @open-sauced/engineering any thoughts on what it would take to do this? Is there anywhere that it's critical we get a complete snapshot of _all_ PRs in a given time range?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This endpoint is most likely a carryover. This endpoint is being used in the client app, and there aren't any places currently where we want a feed of all prs in a given time window.

**Comment by jpmcb** [comment]
Cool: I'll go ahead and remove it in `v2` 👍🏼

**Comment by jpmcb** [comment]
Closed by #501
