### ISSUE TITLE
Feature: workspaces stats endpoint

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#520]
### Type of feature

🍕 Feature

### Current behavior

We'll want an aggregate endpoint that grabs stats for:
- pull requests opened
- pull requests merged
- pull request velocity
- issues opened
- issues closed
- issue velocity
- repo stars
- repo forks
- repo health

across all repos found in `workspaces_repos` for a given workspace

### Suggested solution

Something like this (as suggested by @nickytonline)

```json5
{
  pull_requests: {
    opened: 10,
    merged: 5,
    velocity: 2,
  },
  issues: {
    opened: 10,
    closed: 5,
    velocity: 2,
  },
  repos: {
    stars: 4530,
    forks: 87,
    health: 7,
  }
}
```

On a

```
GET /v2/workspaces/{id}/stats
```

endpoint.

---

Note: this will aggregate stats for repos tracked / found in the workspace's `workspace_repo` join table, not the individual insight pages for a workspace. This will also require some work to stub out the calculations suggested in https://github.com/open-sauced/engineering/issues/37 for the [Winsorized](https://en.wikipedia.org/wiki/Winsorizing) repos health

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Thanks for opening this @jpmcb.

`GET /v2/workspaces/{id}/stats` makes sense as long as we don't have statistics for contributors (not sure if we plan to @isabensusan @bdougie?). If we do, then I'd go with `GET /v2/workspaces/{id}/repo-stats`.
