### ISSUE TITLE
feat: Make workspaces public (with ability to make them private w/ pricing)

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#575]
> As a user, I should have an option to switch my workspace to private (with paid upgrade).

![Screen Shot 2024-02-16 at 10 48 24 AM](https://github.com/open-sauced/app/assets/5713670/13086275-7d9e-43c1-91ab-0fff9f14f282)

_Originally posted by @bdougie in https://github.com/open-sauced/app/issues/2651#issuecomment-1949110205_
            
---

We need workspaces to be able to be public by default (and then allow users to flip them to be private).

**Comment by bdougie** [comment]
For clarification. I think the default should be private and a setting appears in onboarding.

**Comment by jpmcb** [comment]
Sounds like workspaces will actually all be public by default: paying makes them able to be private.
