### ISSUE TITLE
Feature: make deleting personal workspace impossible

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#578]
### Type of feature

🍕 Feature

### Current behavior

Followup to: https://github.com/open-sauced/app/pull/2709

---

Currently, someone would be able to delete their personal workspace via the API. We should ideally not allow this since it's expected that all users have a personal workspace at all times.

### Suggested solution

Add a check here for the personal workspace ID on the user:

https://github.com/open-sauced/api/blob/3b99e0655ca8f2b7982b1e7595bfaab25ebe47b4/src/workspace/workspace.service.ts#L274-L284

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The suggested logic makes sense to me. 🚀
