### ISSUE TITLE
Feature: change "Personal Workspace" title on personal workspace

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/api#608]
### Type of feature

🍕 Feature

### Current behavior

Personal workspaces by default are called "Personal Workspace", and it feels a bit confusing and detached for the user
<img width="1400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/d5290c5d-8ed4-4741-95e0-45163816cc22">

### Suggested solution

I have two different proposals for this:
1. (Ideal) Can we make default workspaces names "<User's> Name"? Like "Isa's Workspace"
2. Alternatively, can we make them say "Your workspace" instead? I think that'd be better at least.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Here's what i came up with @nickytonline - this updates all workspace records where the personal workspace name has gone unmodified:

```sql
-------------------------------------------------------------------------------
-- A one off modification to unchanged workspace names/descriptions
-- to update the copy for users
-------------------------------------------------------------------------------

-- Declare a function to loop through workspaces and modify personal workspace
-- names / descriptions for those that have not been modified.
create or replace function update_personal_workspaces_names_for_users()
returns void as $$
declare
    workspace_record record;
begin
    for workspace_record in select id from workspaces where name = 'Personal workspace' loop
    
		update workspaces set
		name = 'Your workspace',
		description = 'Your personal workspace',
		updated_at = now()
		where id = workspace_record.id;

    end loop;
end;
$$ language plpgsql;

-- Execute the function
select update_personal_workspaces_names_for_users();
```

Also ran this on a local copy of the dev database and works as expected 👍🏼 

```
id: 2f545d26-2f39-4292-bb4b-6354abf4e88b
created_at: 2024-02-29 02:14:21.898503
updated_at: 2024-02-29 02:15:43.148104
deleted_at: NULL
name: Your workspace
description: Your personal workspace
is_public: true
payee_user_id: NULL
```

---

Also happy to take this on: I think I have a good idea where all the modificatiosn are need in code.

**Comment by nickytonline** [comment]
Sounds good @jpmcb. Thanks!
