### ISSUE TITLE
Feature: implement `repo/{org}/{name}/info`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#750]
### Current behavior

Now that we have some heavier calculations in `repo/{org}/{name}` we may see some slowdown when small, quick operations (like just checking the repo exists) to be completed

### Suggested solution

Create a `repos/{owner}/{repo}/peek` endpoint that surfaces just abit of info.

@nickytonline also mentioned just adding a `minimalInfo` param that denotes the `repos/{owner}/{repo}` endpoint should just return repo name, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Chatted with @jpmcb briefly and we're going to go with `repo/{org}/{name}/info`.
