### ISSUE TITLE
StarSearch: Turn down the bing response weight

### ISSUE THREAD

**Issue by bdougie** [open-sauced/api#792]
Every response for StarSearch is bing powered right now. Perhaps we can update the prompt to use bing as a enhancer or if nothing is found. 

![Screenshot 2024-05-13 at 12 17 17 PM](https://github.com/open-sauced/api/assets/5713670/fa6e18ef-433e-445f-9274-cec1ca02130b)

## Expectation

Bing is providing links to articles. I'd expect to see link to GitHub users like it previously

**Comment by bdougie** [comment]
@jpmcb looks like this is not a problem on Beta. Did you already address this?
 
![Screenshot 2024-05-13 at 12 56 03 PM](https://github.com/open-sauced/api/assets/5713670/63a1f812-eddc-412f-acbc-cc926f04196e)

**Comment by jpmcb** [comment]
Need to evaluate this since I added a line to tell the model to only use Bing as a "LAST RESORT": #795 - will close this once we feel this is good
