### ISSUE TITLE
Bug: Lottery factor with no contributions over time range returns "Low" lottery factor

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/api#808]
### Describe the bug

Found an interesting edge case with the Lottery factor algorithm when investigating #804:

If a repository _does exist_ but it's had zero contributions in the given time range, it'll return the following chunk:

```json
{
  "all_contribs": [],
  "all_lotto_factor": "low"
}
```

For example, for one of my projects `jpmcb/gopherlogs` that I haven't made changes to in awhile returns this:

```
curl -X 'GET' \
  'https://api.opensauced.pizza/v2/repos/lotto?repos=jpmcb%2Fgopherlogs&range=30&prev_days_start_date=0' \
  -H 'accept: application/json'

{
  "all_contribs": [],
  "all_lotto_factor": "low"
}
```

This should be a relatively easy fix once we decide on how to approach this scenario.

### Proposal: treat _no_ contributions as a very high lottery factor

In the best case scenario, if a project hasn't gotten alot of love recently, everyone's on vacation or on holiday during Christmas break or something. In the worst case scenario, the one person who has merge access on the repo isn't around anymore and no new changes can go in.

Therefore, I propose we mark this scenario as _"very high"_. Thoughts @open-sauced/engineering ?

### Steps to reproduce

1. Use the `/v2/repos/lotto` endpoint with a repo that hasn't gotten love recently
2. Notice it returns "all_lotto_factor" of low.

**Comment by bdougie** [comment]
Curious at what point we show this image, or if it is event needed? https://github.com/open-sauced/app/pull/3343#issuecomment-2105131574

**Comment by brandonroberts** [comment]
I would think it would be for relatively new repositories. If I create a brand new repo and haven't started working on it yet, maybe there's a grace period of 30 days from the repository creation date if it has no data.

**Comment by jpmcb** [comment]
I like the idea of a grace period for new repos: I can experiment quick with that and the "creation date" we have from the metadata in the repos data. And likely set a new field in the payload for "grace_period"
