### ISSUE TITLE
Feature: Track repository topics and languages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/api#9]
### Type of feature

🍕 Feature

### Current behavior

The new insights product will eventually filter by knowledge of topics and languages. We should also store that data for filtering purposes.

### Suggested solution

Add two columns for the repo table the array for languages and topics

<img width="367" alt="Screen Shot 2022-07-31 at 8 27 37 PM" src="https://user-images.githubusercontent.com/5713670/182066302-b0cb87d9-5dea-478f-b92d-495c29696b7f.png">

<img width="348" alt="Screen Shot 2022-07-31 at 8 27 55 PM" src="https://user-images.githubusercontent.com/5713670/182066342-98fe497e-84ca-43de-bb70-f694bc20df05.png">
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Will check to see how to add this data in the backend ASAP

**Comment by diivi** [comment]
Can this be closed now? looks like we added [topics](https://github.com/diivi/api.opensauced.pizza/blob/cc526bcbe56c41885c61dcec4ebe78fff8594aca/src/repo/entities/repo.entity.ts#L388) and [language](https://github.com/diivi/api.opensauced.pizza/blob/cc526bcbe56c41885c61dcec4ebe78fff8594aca/src/repo/entities/repo.entity.ts#L345) to the repo entity.

**Comment by bdougie** [comment]
Yes
